site_name: thautils
site_author: C.Thang Nguyen
# repo_url: ""
# edit_uri: "https://github.com/thangckt/src_thatool/tree/main/docs"
docs_dir: _docs

## Copyright
copyright: Copyright &copy; 2022 <a href="https://thangckt.github.io">thangckt</a>

## Configuration
theme:
  name: "material" #  "material"    "mkdocs"    "readthedocs"     'rtd-dropdown'   windmill  bootswatch
  custom_dir: _docs/_overrides
  logo: 1images/one-note-128-o.png # snake1.png
  favicon: 1images/one-note-128-o.png
  highlightjs: true
  features:
    - content.code.annotate
    # - navigation.expand
    # - navigation.sections
    - navigation.indexes
    # - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - toc.follow
    # - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.header # only in extended theme
    ### new in v9
    # - content.action.edit
    - navigation.footer

  palette:
    scheme: slate

    # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    # scheme: default
    # primary: blue grey   #  blue grey, indigo
    # accent: indigo
    # toggle:
    #   icon: material/lightbulb
    #   name: Switch to dark mode
    # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    # scheme: slate
    # primary: blue grey   #  blue grey, indigo
    # accent: indigo
    # toggle:
    #   icon: material/lightbulb-outline
    #   name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

### Extra theme
extra_javascript:
  - _extra_theme/extra_js/gg_adsense.js
extra_css:
  - _extra_theme/extra_css/full_width.css
  - _extra_theme/extra_css/font_size.css

## Customization
extra:
  generator: false
  analytics:
    provider: google
    property: G-QM7DWGY7ZT
  social:
    # - icon: fontawesome/solid/envelope
    #   link: mailto:<name@something.com>
    #   name: Email to thangckt
    # - icon: fontawesome/brands/telegram
    #   link: https://t.me/thangckt
    #   name: thangckt on Telegram
    # - icon: fontawesome/brands/facebook
    #   link: https://www.facebook.com/thangckt5
    #   name: thangckt on Facebook
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/thangckt
    #   name: thangckt on Linkedin
    # - icon: fontawesome/brands/orcid
    #   link: https://orcid.org/0000-0001-9826-5397
    #   name: thangckt on ORCID
    # - icon: fontawesome/brands/discord
    #   link: https://discord.com/channels/@thangckt#9473
    #   name: thangckt on Discord
    # - icon: fontawesome/brands/github
    #   link: https://github.com/thangckt
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/squidfunk

  # version:
  #   provider: mike
  #   default: latest

## Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - codehilite
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

## Plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options: # https://mkdocstrings.github.io/python/usage/#globallocal-options
            show_root_heading: true
            show_category_heading: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
            show_signature_annotations: true
            inherited_members: true # member options
            members_order: "source"
            filters: ["!^_[^_]"]
            show_submodules: true
            summary: true
            docstring_style: "google" # Docstrig options: google, numpy, sphinx
            docstring_section_style: "list" # 'table', 'list', 'spacy'
            show_if_no_docstring: true
            merge_init_into_class: true
          # path: [.]
          # import:
          #   - https://docs.python.org/3/objects.inv
          #   - https://mkdocstrings.github.io/autorefs/objects.inv

###=======================================
### Site content
###=======================================
## Page tree
nav:
  - home: http://thangckt.github.io
  # - molbuilder: https://thangckt.github.io/molbuilder
  - thamd: http://thangckt.github.io/thamd_doc
  - thaml: http://thangckt.github.io/thaml_doc
  - thvid: http://thangckt.github.io/thvid_doc

  - thutils:
      - About: index.md
      - general.md
      - io.md
      - sth2sth.md
  - almace: http://thangckt.github.io/almace_doc

  - cluster: http://thangckt.github.io/cluster
  - refs: http://thangckt.github.io/ref
  - odd: http://thangckt.github.io/odd
  - blog: http://thangckt.github.io/blog

  # - NextChat: http://chat-gpt-next-lvkto5aam-thangcktgmailcoms-projects.vercel.app
  # - llm: http://thangckt.github.io/llm
  # - 1click_BibTeX: https://thang.eu.org/blog/2024/01/25/bibtex_generator/
  - tv: http://thangckt.github.io/tv/
  - contact: http://thangckt.github.io/contact
