name: mkdocs gh-deploy

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "dev_tool/**"
      - "*.egg-info/**"
      - "dist/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: fetch extra javascript
        run: |
          python _docs/_script/fetch_js.py

      - name: Install dependencies # mkdocs-jupyter can cause broken in tabs-header
        run: |
          pip install git+https://github.com/thangckt/mkdocs-material.git@main     # main  v9.4.9 tabs_header_yinkh
          pip install mkdocstrings[python]>=0.24

          # pip install mkdocs-jupyter # conflict
          # pip install mkdocs-enumerate-headings-plugin #  mkdocs

      - name: MkDocs build & deploy site # This will create `gh-pages` branch contain `mkdocs-site`. See https://www.mkdocs.org/user-guide/cli/#mkdocs-gh-deploy
        run: mkdocs gh-deploy --force --verbose
